change keydir to standard /usr/share/keyrings

diff --git a/api b/api
--- a/api
+++ b/api
@@ -365,25 +365,25 @@ add_external_repo() { # add an external apt repo and its gpg key
   wget -q --spider "$pubkeyurl" || error "add_external_packages: pubkeyurl isn't a valid link"
 
   # make pi-apps key storage dir if it doesn't exist
-  if [ ! -d /opt/pi-apps-apt-keys ]; then
-    mkdir -p /opt/pi-apps-apt-keys || error "add_external_repo: failed to create pi-apps key storage dir."
+  if [ ! -d /usr/share/keyrings ]; then
+    mkdir -p /usr/share/keyrings || error "add_external_repo: failed to create pi-apps key storage dir."
   fi
 
   # check if .list file already exists
   [ -f /etc/apt/sources.list.d/${reponame}.list ] && error "add_external_repo: /etc/apt/sources.list.d/${reponame}.list already exists."
 
   # download gpg key from specified url
-  rm -f /opt/pi-apps-apt-keys/${reponame}-keyring.gpg
-  wget -q "$pubkeyurl" -O /opt/pi-apps-apt-keys/${reponame}-keyring.gpg || error "add_external_repo: download from specified pubkeyurl failed."
+  rm -f /usr/share/keyrings/${reponame}-keyring.gpg
+  wget -q "$pubkeyurl" -O /usr/share/keyrings/${reponame}-keyring.gpg || error "add_external_repo: download from specified pubkeyurl failed."
 
   # create .list file
-  echo "deb [signed-by=/opt/pi-apps-apt-keys/$reponame-keyring.gpg] $repopath" | sudo tee /etc/apt/sources.list.d/${reponame}.list >/dev/null || error "add_external_repo: failed to create .list file"
+  echo "deb [signed-by=/usr/share/keyrings/$reponame-keyring.gpg] $repopath" | sudo tee /etc/apt/sources.list.d/${reponame}.list >/dev/null || error "add_external_repo: failed to create .list file"
 }
 
 rm_external_repo() { # remove an external apt repo and its gpg key
   reponame="$1"
 
-  rm -f /opt/pi-apps-apt-keys/${reponame}-keyring.gpg || error "rm_external_repo: removal of ${reponame}-keyring.gpg failed"
+  rm -f /usr/share/keyrings/${reponame}-keyring.gpg || error "rm_external_repo: removal of ${reponame}-keyring.gpg failed"
 
   sudo rm -f /etc/apt/sources.list.d/${reponame}.list || error "rm_external_repo: removal of ${reponame}.list failed"
 }
